
num_channels_scalar: 10

num_channels_m:
  - 
    - 256
  - 
    - 256
  - 
    - 256
  - 
    - 256
  - 
    - 256
num_channels_2to2: 
  - 192
  - 192
  - 192
  - 192
  - 192
num_channels_m_out:
  - 256
  - 192
num_channels_out: 
  - 256